import type { Metadata } from "next";

import "./globals.css";
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "lilblackboot",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en" >
      <body>

      </body>
    </html>
  );
}
